name: qasa-backend

services:
  postgres:
    image: postgres:16-alpine
    container_name: qasa-postgres
    ports:
      - "5430:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-qasa_db}
      POSTGRES_USER: ${POSTGRES_USER:-qasa_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qasa_password}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qasa-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-qasa_user} -d ${POSTGRES_DB:-qasa_db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    profiles: ["dev", "prod"] # disponible en ambos entornos

  qasa-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: qasa-backend
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
      - "${DEBUG_PORT:-9229}:9229"
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - /app/node_modules
    environment:
      NODE_ENV: development
      APP_ENV: development
      HOST: 0.0.0.0
      PORT: ${PORT:-3000}
      LOG_LEVEL: debug
      CORS_ALLOWED_ORIGINS: "*"

      # Prisma necesita esto sí o sí
      DATABASE_URL: postgresql://${POSTGRES_USER:-qasa_user}:${POSTGRES_PASSWORD:-qasa_password}@postgres:5432/${POSTGRES_DB:-qasa_db}?schema=public

      DEBUG_EXPOSE: ${DEBUG_PORT:-9229}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - qasa-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://0.0.0.0:${PORT:-3000}/health",
          "||",
          "exit",
          "1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    profiles:
      - dev

  qasa-backend-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: qasa-backend-prod
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      APP_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      LOG_LEVEL: info
      CORS_ALLOWED_ORIGINS: "*"

      # Prisma in prod (local emulation)
      DATABASE_URL: postgresql://${POSTGRES_USER:-qasa_user}:${POSTGRES_PASSWORD:-qasa_password}@postgres:5432/${POSTGRES_DB:-qasa_db}?schema=public
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - qasa-network
    profiles:
      - prod
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://0.0.0.0:3000/health",
          "||",
          "exit",
          "1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  qasa-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  node_modules:
    driver: local
